import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "react-hot-toast";
import { ThemeProvider } from "@/providers/theme-provider";
import { auth } from "@/auth";
import { ModalProvider } from "@/providers/modal-provider";
import { currentUser } from "@/lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth();
  const user = await currentUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Toaster/>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
          >
            <ModalProvider 
              //@ts-ignore
              currentUser={user}
            />
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
